name: mt7623
vendor: Mediatek Inc. <woodrow.shen@canonical.com>
icon: meta/mediatek.png
version: 0.12
type: oem
architectures: [armhf]
frameworks:
    - ubuntu-core-15.04-dev1

config:
  ubuntu-core:
    hostname: mt7623
    services:
        - name: ssh
          enabled: true
    autopilot: false

oem:
  branding:
    name: MT7623board
    logo: meta/mediatek.png
  software:
    preinstalled:
        - webdm
  hardware:
    platform: mt7623
    architecture: armhf
    partition-layout: system-AB
    bootloader: u-boot
    boot-assets:
      files:
        - path: boot-assets/uEnv.txt
      raw-files:
        - path: boot-assets/bromhdr-0.bin
          offset: 0
        - path: boot-assets/bromhdr-1.bin
          offset: 512
        - path: boot-assets/preloader_iotg7683p1_emmc.bin
          offset: 2048 # 2K
        - path: boot-assets/u-boot.bin
          offset: 327680 # 320 * 1K
